# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Guide Stampanti 3D
    url: tag/guide-comparative-stampanti-3d/
    weight: 10
  - name: Analisi modelli Stampanti 3D
    url: tag/analisi-modelli-stampanti-3d/
    weight: 20
  - name: Categorie
    url: tags/
    weight: 30
  - name: Su di me
    url: su-di-me/
    weight: 40
