# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: cyan

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'modeltoreal.com'
    description: 'Benvenut@ a Model to Real, il sito sulle stampanti 3D in cui troverai guide, analisi e consigli utili per trasformare le tue idee in realtà.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: left
    logo:
      filename: 'logo.png'
    show_search: true
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} modeltoreal.com'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/diletta-ci/modeltoreal-hugoblox'
    content_dir: starters/blog/content
    branch: main
